------------------
```markdown
# Copyright © 2024 Meysam Goodarzi
This notebook is licensed under CC BY-NC 4.0 with the following amandments:
- Individuals may use, share, and adapt this material for non-commercial purposes with attribution.
- Institutions/Companies must obtain written consent to use this material, except for nonprofits.
- Commercial use is prohibited without permission.  
Contact: analytica@meysam-goodarzi.com
```
------------------------------
❗❗❗ **IMPORTANT**❗❗❗ **Create a copy of this notebook**

In order to work with this Google Colab you need to create a copy of it. Please **DO NOT** provide your answers here. Instead, work on the copy version. To make a copy:

**Click on: File -> save a copy in drive**

Have you successfully created the copy? if yes, there must be a new tab opened in your browser. Now move to the copy and start from there!

----------------------------------------------

# Transformations
This notebooks is dedicated to the introduction of transformations in Pandas. Transformations are operations that modify data in a DataFrame or Series. These can include defining/droping/editing columns and applying functions.

Let us begin by importing the neccessary libraries import the dataset from the car manufacturing.

In [21]:
import pandas as pd
import numpy as np

In [22]:
df = pd.read_csv("https://raw.githubusercontent.com/juliandnl/redi_ss20/master/cars.csv")

## Simple Operations in Pandas
There are simple operations that can be done to slightly change the data set. These could be summarized as:

* Creating a new column (with or without value)
* Overwriting pre-existing data
* Defining a new column based on an exisitng column
* Dropping one or more columns/rows

#### Example
Let us see how each simple operation mentioned above can be implemented:

* Creating a new column (with or without value)
* Overwriting pre-existing data

In [23]:
df['Cost'] = None
df.head(5)

# Set the "Cost" column such that cost is equal to the 70% of the price.
# Your code

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,Cost
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360000,4.0,Sedán,Córdoba,None
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320000,2.0,Pick-Up,Entre Ríos,None
2,Volkswagen,Fox,2011,1.6 Trendline,132000,209980,5.0,Hatchback,Bs.as. G.b.a. Sur,None
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798000,4.0,Pick-Up,Neuquén,None
4,Volkswagen,Gol,2013,1.4 Power 83cv 3 p,107000,146000,3.0,Hatchback,Córdoba,None

* Defining a new column based on an exisitng column

In [24]:
df['Profit'] = df['Price'] - df['Cost']
df[['Price', 'Cost', 'Profit']].head(5)

# Define a new column called "MM" which adds the strings from "Make" and "Model"
# in the form Make + "_" + Model

df['MM'] = df['Make'] + "_" + df['Model']
df[['Make', 'Model', 'MM']].head(5)

         Make   Model                MM
0  Volkswagen   Vento  Volkswagen_Vento
1        Ford  Ranger       Ford_Ranger
2  Volkswagen     Fox    Volkswagen_Fox
3        Ford  Ranger       Ford_Ranger
4  Volkswagen     Gol    Volkswagen_Gol

In [ ]:
df["MM"] = df["Make"] + "_" + df["Model"]
df[["Make", "Model", "MM"]].head(5)

* Dropping one or more columns/rows

In [ ]:
# df = df.drop(columns=['Cost'])
df.head(5)

# Drop the "MM" column

df

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,Profit
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360000,4.0,Sedán,Córdoba,NaN
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320000,2.0,Pick-Up,Entre Ríos,NaN
2,Volkswagen,Fox,2011,1.6 Trendline,132000,209980,5.0,Hatchback,Bs.as. G.b.a. Sur,NaN
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798000,4.0,Pick-Up,Neuquén,NaN
4,Volkswagen,Gol,2013,1.4 Power 83cv 3 p,107000,146000,3.0,Hatchback,Córdoba,NaN
...,...,...,...,...,...,...,...,...,...,...
9995,Ford,Focus III,2016,2.0 Se,67000,399000,5.0,Hatchback,Bs.as. G.b.a. Oeste,NaN
9996,Volkswagen,Bora,2012,1.9 Trendline I 100cv,120000,240000,4.0,Sedán,Buenos Aires Interior,NaN
9997,Ford,Fiesta Kinetic Design,2012,1.6 Design 120cv Titanium,89000,250000,5.0,Hatchback,Tucumán,NaN
9998,Ford,Fiesta Kinetic Design,2013,1.6 Design 120cv Titanium,76000,295000,5.0,Hatchback,Buenos Aires Interior,NaN
9999,Ford,Focus III,2014,2.0 Titanium At6,32000,380000,5.0,Hatchback,Bs.as. G.b.a. Sur,NaN

In [ ]:
# df = df.drop(columns=['MM'])

**Question**: What is the difference between `df = df.drop(columns=['Cost'])` and `df.drop(columns=['Cost'])`?

**Hint**: Check the [drop()](https://www.w3schools.com/python/pandas/ref_df_drop.asp).

### Conditionals on DataFrames
Pandas allows us to apply conditionals on DataFrames using methods from numpy library, i.e., `np.where()` and `np.select()`. These methods allow us to define new columns based on certain conditions. Their functionalites are as follows

* `np.where()`:  Allows for performing an element-wise conditional operation in a DataFrame.
* `np.select()`: Allows for multiple conditions to be applied at once, useful for creating more complex conditionals.

#### Example
Define a new column Discounted that marks cars as "Yes" if their Price is above 20,000 and "No" otherwise.

In [ ]:
df['Discounted'] = np.where(
    # code
    )
df[['Model', 'Price', 'Discounted']].head()

    Model   Price Discounted
0   Vento  360000        Yes
1  Ranger  320000        Yes
2     Fox  209980        Yes
3  Ranger  798000        Yes
4     Gol  146000        Yes

In [ ]:
df['Price'] > 20000, "Yes", "No"

#### Example
Define a column Price_Category with the following rules:

* If Price is above 30,000, label it as "High".
* If Price is between 15,000 and 30,000, label it as "Medium".
* Otherwise, label it as "Low".

In [13]:
conditions = [
    (df['Price'] > 30000),
    (df['Price'] <= 30000) & (df['Price'] >= 15000),
    (df['Price'] < 15000)
]

choices = ['High', 'Medium', 'Low']

df['Price_Category'] = np.select(
    conditions, choices, default='Unknown'
    )
print(df[['Model', 'Price', 'Price_Category']].head())

    Model   Price Price_Category
0   Vento  360000           High
1  Ranger  320000           High
2     Fox  209980           High
3  Ranger  798000           High
4     Gol  146000           High

#### Exercise 1
Define a column called "New" which takes the value 1 if the car's production year is greater than 2017 and 0 otherwise.

In [14]:
df['New'] = np.where(
    df['Year'] > 2017,
    1,
    0
    )
df[['Year', 'New']].head(5)

   Year  New
0  2012    0
1  2012    0
2  2011    0
3  2017    0
4  2013    0

#### Exercise 2
Define a column "Age_Category" with the following rules:

* If the Kms is below 15000, label it as "new".
* If the Kms is between 15000 and 50000, label it as "relatively new".
* If the Kms is between 40000 and 100000, label it as "old".
* If the Kms is above 100000, label it as "too old".

In [15]:
conditions = [
   df["Kms"] < 15000,
   df["Kms"] < 50000,
   df["Kms"] < 100000,
   df["Kms"] > 100000,

]

choices = ['new', 'relatively new', 'old', 'too old']

df['Price_Category'] = np.select(
    conditions, choices, default='Unknown'
    )
print(df[['Model', 'Price', 'Price_Category']].head())

    Model   Price Price_Category
0   Vento  360000            old
1  Ranger  320000        too old
2     Fox  209980        too old
3  Ranger  798000            new
4     Gol  146000        too old

## Applying Functions
The following methods are most commonly used to perfrom transformations:

* `apply()`: Applies a function along an axis (rows or columns).
* `map()`: Maps values from a dictionary or a function to replace values in a panda Series.
* `replace()`: Replaces values in a DataFrame or Series with a specified value or pattern.

#### Example
Create an abbreviation of the `Make` of a car. Create a new column `Brand` that contains the first 3 letters in uppercase of the value from the `Make` columns.

Example: Iff `Make` is `Chrysler`, `Brand` should be `CHR`.

1. Use `apply` with a regular `def` function
1. Use `lambda` function
2. Use only dataframe built-in functionality

In [16]:
def create_abbrev(make):
    """Creates the abbreviation from a full name.

      Args:
        make: A string containing the full word.

      Returns:
        A string containing the abbreviation.
    """
    return make.upper()[:3]

df['Brand'] = df['Make'].apply(
    create_abbrev
)

In [19]:
df["Brand"][:2]

0    VOL
1    FOR
Name: Brand, dtype: str

In [ ]:
# Lambda implementation
df.loc[:, 'Brand'] = df.loc[:, 'Make'].apply(
    lambda make: # Your code
)

In [12]:
# Pandas built-in methods
df.loc[:, 'Brand'] = df.loc[:, 'Make'].str[0:3].str.upper()
df.head(5)

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,Profit,New,Brand
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360000,4.0,Sedán,Córdoba,NaN,0,VOL
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320000,2.0,Pick-Up,Entre Ríos,NaN,0,FOR
2,Volkswagen,Fox,2011,1.6 Trendline,132000,209980,5.0,Hatchback,Bs.as. G.b.a. Sur,NaN,0,VOL
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798000,4.0,Pick-Up,Neuquén,NaN,0,FOR
4,Volkswagen,Gol,2013,1.4 Power 83cv 3 p,107000,146000,3.0,Hatchback,Córdoba,NaN,0,VOL

#### Example
Map car brands to regions using a dictionary.

<!--
# Copyright © 2024 Meysam Goodarzi
This notebook is licensed under CC BY-NC 4.0 with the following amandments:
- Individuals may use, share, and adapt this material for non-commercial purposes with attribution.
- Institutions/Companies must obtain written consent to use this material, except for nonprofits.
- Commercial use is prohibited without permission.  
Contact: analytica@meysam-goodarzi.com.
-->

In [ ]:
brand_region = {
    'Volkswagen': 'Europe', 'Ford': 'North America', 'Mercedes Benz': 'Europe',
    'Honda': 'East Asia', 'Chrysler': 'North America'
    }

df['Region'] = df['Make'].map(
    # Your code
)
print(df[['Make', 'Region']].head(5))

#### Example
Replace the values in the Region column from "East Asia" to "Asia".

In [ ]:
df['Region'] = df['Region'].replace(
    # Your code
)
df.head(5)

#### Exercise 3
Create a new column which calculates the amount of tax per car depending on the year of production for 2024. Use the tax rate of $2.5\%$ for each year.

Example: for Year = 2014 the tax rate would be (2024-2014)*2.5

Perform the task using the `lambda` function.

In [ ]:
df['Tax'] = df.apply(
    lambda row: # Your code,
    axis=1
    )

df[['Year', 'Price', 'Tax']].head(5)

#### Exercise 4
Map car brands to their respective countries using a dictionary and lambda function.

In [ ]:
brand_region = {
    'Volkswagen': 'Germany', 'Ford': 'US', 'Mercedes Benz': 'Germany',
    'Honda': 'Japan', 'Chrysler': 'US'
    }
# Your code
df[['Make', 'Region']].head(5)

In [ ]:
df["Country"] = df["Make"].map(
    lambda make: # Your code
)

**Congratulations! You have finished the Notebook! Great Job!**
🤗🙌👍👏💪
<!--
# Copyright © 2024 Meysam Goodarzi
This notebook is licensed under CC BY-NC 4.0 with the following amandments:
- Individuals may use, share, and adapt this material for non-commercial purposes with attribution.
- Institutions/Companies must obtain written consent to use this material, except for nonprofits.
- Commercial use is prohibited without permission.  
Contact: analytica@meysam-goodarzi.com.
-->