# Class Content

1. Simple column operations
2. Custom row-wise transformations
3. Concatenating dataframes
4. Joining dataframes

# Let's remember the 'cars' Dataframe:
The dataframe contains the information of 10.000 cars. There are 9 different columns:
- Make (Car brand, example: Ford)
- Model (The Model of the Car, example: Focus)
- Year (The Year in which the car was build, example: 2012)
- Variant (The car model version showing the PS, example: 1.6 Trendline)
- Kms (The kilometers the cars has been driven, example: 90000)
- Price (The offered price for the car, example: 10000)
- Doors (How many doors the car has, example: 4)
- Kind (Type of car, example: Pick-Up)
- Location (Where the car is located, example: Buenos Aires)

In [ ]:
import pandas as pd
import numpy as np

# this is a hack to allow displaying more than one result per notebook cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
cars = pd.read_csv("https://raw.githubusercontent.com/juliandnl/redi_ss20/master/cars.csv")

In [ ]:
cars.head(3)

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360000,4.0,Sedán,Córdoba
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320000,2.0,Pick-Up,Entre Ríos
2,Volkswagen,Fox,2011,1.6 Trendline,132000,209980,5.0,Hatchback,Bs.as. G.b.a. Sur

In [ ]:
cars.shape

(10000, 9)

# Simple column operations

### Create an empty new variable

In [ ]:
cars.loc[:, 'test'] = None

In [ ]:
cars['test1'] = None

In [ ]:
cars.shape

(10000, 10)

In [ ]:
cars.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,test,test1
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360000,4.0,Sedán,Córdoba,None,None
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320000,2.0,Pick-Up,Entre Ríos,None,None
2,Volkswagen,Fox,2011,1.6 Trendline,132000,209980,5.0,Hatchback,Bs.as. G.b.a. Sur,None,None
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798000,4.0,Pick-Up,Neuquén,None,None
4,Volkswagen,Gol,2013,1.4 Power 83cv 3 p,107000,146000,3.0,Hatchback,Córdoba,None,None

### Create a new variable with some value

In [ ]:
cars.loc[1:2,:]

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,test,test1,new_data
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320000,2.0,Pick-Up,Entre Ríos,None,None,1.0
2,Volkswagen,Fox,2011,1.6 Trendline,132000,209980,5.0,Hatchback,Bs.as. G.b.a. Sur,None,None,1.0

In [ ]:
cars.loc[1:2, 'new_data'] = 1

In [ ]:
cars.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,test,test1,new_data
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360000,4.0,Sedán,Córdoba,None,None,NaN
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320000,2.0,Pick-Up,Entre Ríos,None,None,1.0
2,Volkswagen,Fox,2011,1.6 Trendline,132000,209980,5.0,Hatchback,Bs.as. G.b.a. Sur,None,None,1.0
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798000,4.0,Pick-Up,Neuquén,None,None,NaN
4,Volkswagen,Gol,2013,1.4 Power 83cv 3 p,107000,146000,3.0,Hatchback,Córdoba,None,None,NaN

In [ ]:
cars.loc[:, 'new_data'] = 1

cars.head(10)

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,test,test1,new_data
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360000,4.0,Sedán,Córdoba,None,None,1.0
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320000,2.0,Pick-Up,Entre Ríos,None,None,1.0
2,Volkswagen,Fox,2011,1.6 Trendline,132000,209980,5.0,Hatchback,Bs.as. G.b.a. Sur,None,None,1.0
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798000,4.0,Pick-Up,Neuquén,None,None,1.0
4,Volkswagen,Gol,2013,1.4 Power 83cv 3 p,107000,146000,3.0,Hatchback,Córdoba,None,None,1.0
5,Volkswagen,Amarok,2014,2.0 Cd Tdi 180cv 4x4 Highline C34,115000,790000,4.0,Pick-Up,Buenos Aires Interior,None,None,1.0
6,Ford,Ka,2012,1.0 Fly Viral 63cv,95243,142000,3.0,Hatchback,Bs.as. G.b.a. Sur,None,None,1.0
7,Ford,Ka,2012,1.6 Fly Viral 95cv,110000,148000,3.0,Hatchback,Buenos Aires Interior,None,None,1.0
8,Ford,Focus III,2017,1.6 S,17500,367000,5.0,Hatchback,Buenos Aires Interior,None,None,1.0
9,Ford,Fiesta Kinetic Design,2014,1.6 Sedan Titanium Powershift 120cv,43000,287000,4.0,Sedán,Bs.as. G.b.a. Norte,None,None,1.0

### Overwrite pre-existing data

In [ ]:
cars['new_data'] = 2
cars.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,test,test1,new_data
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360000,4.0,Sedán,Córdoba,None,None,2
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320000,2.0,Pick-Up,Entre Ríos,None,None,2
2,Volkswagen,Fox,2011,1.6 Trendline,132000,209980,5.0,Hatchback,Bs.as. G.b.a. Sur,None,None,2
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798000,4.0,Pick-Up,Neuquén,None,None,2
4,Volkswagen,Gol,2013,1.4 Power 83cv 3 p,107000,146000,3.0,Hatchback,Córdoba,None,None,2

### New column based on exisitng column

In [ ]:
import datetime

# get current year
year = datetime.date.today().year
year

2024

In [ ]:
cars.loc[:, 'Year']

0       2012
1       2012
2       2011
3       2017
4       2013
        ...
9995    2016
9996    2012
9997    2012
9998    2013
9999    2014
Name: Year, Length: 10000, dtype: int64

In [ ]:
# calculate YTD = years-to-date (age of the car)
cars.loc[:, 'YTD'] = year - cars.loc[:, 'Year']

In [ ]:
cars.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,test,test1,new_data,YTD
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360000,4.0,Sedán,Córdoba,None,None,hi,12
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320000,2.0,Pick-Up,Entre Ríos,None,None,hi,12
2,Volkswagen,Fox,2011,1.6 Trendline,132000,209980,5.0,Hatchback,Bs.as. G.b.a. Sur,None,None,hi,13
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798000,4.0,Pick-Up,Neuquén,None,None,hi,7
4,Volkswagen,Gol,2013,1.4 Power 83cv 3 p,107000,146000,3.0,Hatchback,Córdoba,None,None,hi,11

In [ ]:
'Volkswagen' + ' ' + 'Vento'

'Volkswagen Vento'

```sql
select concat(make, ' ', model)
from df
```

In [ ]:
# Small exercise: combine the 'Make' (i.e. brand of a car) and 'Model' into a single column
# For example, if the brand is 'Ford' and the model 'Ranger', the new columns should
# be the string 'Ford Ranger'
# Call the column 'brand_model'
cars['brand_model'] = cars['Make'] + ' ' + cars['Model']

In [ ]:
cars.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,test,test1,new_data,YTD,brand_model
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360000,4.0,Sedán,Córdoba,None,None,hi,12,Volkswagen Vento
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320000,2.0,Pick-Up,Entre Ríos,None,None,hi,12,Ford Ranger
2,Volkswagen,Fox,2011,1.6 Trendline,132000,209980,5.0,Hatchback,Bs.as. G.b.a. Sur,None,None,hi,13,Volkswagen Fox
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798000,4.0,Pick-Up,Neuquén,None,None,hi,7,Ford Ranger
4,Volkswagen,Gol,2013,1.4 Power 83cv 3 p,107000,146000,3.0,Hatchback,Córdoba,None,None,hi,11,Volkswagen Gol

In [ ]:
# Convert prices to be represented in thousands (i.e. 360 000 should appear as 360)
cars['Price'] = cars['Price']/1000

In [ ]:
cars.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,test,test1,new_data,YTD,brand_model
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,None,None,hi,12,Volkswagen Vento
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320.00,2.0,Pick-Up,Entre Ríos,None,None,hi,12,Ford Ranger
2,Volkswagen,Fox,2011,1.6 Trendline,132000,209.98,5.0,Hatchback,Bs.as. G.b.a. Sur,None,None,hi,13,Volkswagen Fox
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798.00,4.0,Pick-Up,Neuquén,None,None,hi,7,Ford Ranger
4,Volkswagen,Gol,2013,1.4 Power 83cv 3 p,107000,146.00,3.0,Hatchback,Córdoba,None,None,hi,11,Volkswagen Gol

In [ ]:
# Small exercise: How can we convert kilometers ('Kms') to miles to show them to our British users?
# Round the values to the nearest whole number
miles_per_km = 0.621371

In [2]:
0.621371**-1

1.6093444978925633

In [ ]:
cars['Kms'] * miles_per_km

0       62106.03145
1       86991.94000
2       82020.97200
3        8077.82300
4       66486.69700
           ...
9995    41631.85700
9996    74564.52000
9997    55302.01900
9998    47224.19600
9999    19883.87200
Name: Kms, Length: 10000, dtype: float64

In [ ]:
round(cars['Kms'] * miles_per_km, 0)

0       62106.0
1       86992.0
2       82021.0
3        8078.0
4       66487.0
         ...
9995    41632.0
9996    74565.0
9997    55302.0
9998    47224.0
9999    19884.0
Name: Kms, Length: 10000, dtype: float64

In [ ]:
cars['Miles'] = round(cars['Kms'] * miles_per_km, 0)

In [ ]:
cars.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,test,test1,new_data,YTD,brand_model,Miles
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,None,None,hi,12,Volkswagen Vento,62106.0
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320.00,2.0,Pick-Up,Entre Ríos,None,None,hi,12,Ford Ranger,86992.0
2,Volkswagen,Fox,2011,1.6 Trendline,132000,209.98,5.0,Hatchback,Bs.as. G.b.a. Sur,None,None,hi,13,Volkswagen Fox,82021.0
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798.00,4.0,Pick-Up,Neuquén,None,None,hi,7,Ford Ranger,8078.0
4,Volkswagen,Gol,2013,1.4 Power 83cv 3 p,107000,146.00,3.0,Hatchback,Córdoba,None,None,hi,11,Volkswagen Gol,66487.0

### Dropping one or more columns

In [ ]:
cars.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,test,test1,new_data,YTD,brand_model,Miles
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,None,None,hi,12,Volkswagen Vento,62106.0
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320.00,2.0,Pick-Up,Entre Ríos,None,None,hi,12,Ford Ranger,86992.0
2,Volkswagen,Fox,2011,1.6 Trendline,132000,209.98,5.0,Hatchback,Bs.as. G.b.a. Sur,None,None,hi,13,Volkswagen Fox,82021.0
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798.00,4.0,Pick-Up,Neuquén,None,None,hi,7,Ford Ranger,8078.0
4,Volkswagen,Gol,2013,1.4 Power 83cv 3 p,107000,146.00,3.0,Hatchback,Córdoba,None,None,hi,11,Volkswagen Gol,66487.0

In [ ]:
cars.shape

(10000, 15)

In [ ]:
cars.drop(columns=['test','test1'])

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,new_data,YTD,brand_model,Miles
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,hi,12,Volkswagen Vento,62106.0
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320.00,2.0,Pick-Up,Entre Ríos,hi,12,Ford Ranger,86992.0
2,Volkswagen,Fox,2011,1.6 Trendline,132000,209.98,5.0,Hatchback,Bs.as. G.b.a. Sur,hi,13,Volkswagen Fox,82021.0
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798.00,4.0,Pick-Up,Neuquén,hi,7,Ford Ranger,8078.0
4,Volkswagen,Gol,2013,1.4 Power 83cv 3 p,107000,146.00,3.0,Hatchback,Córdoba,hi,11,Volkswagen Gol,66487.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Ford,Focus III,2016,2.0 Se,67000,399.00,5.0,Hatchback,Bs.as. G.b.a. Oeste,hi,8,Ford Focus III,41632.0
9996,Volkswagen,Bora,2012,1.9 Trendline I 100cv,120000,240.00,4.0,Sedán,Buenos Aires Interior,hi,12,Volkswagen Bora,74565.0
9997,Ford,Fiesta Kinetic Design,2012,1.6 Design 120cv Titanium,89000,250.00,5.0,Hatchback,Tucumán,hi,12,Ford Fiesta Kinetic Design,55302.0
9998,Ford,Fiesta Kinetic Design,2013,1.6 Design 120cv Titanium,76000,295.00,5.0,Hatchback,Buenos Aires Interior,hi,11,Ford Fiesta Kinetic Design,47224.0
9999,Ford,Focus III,2014,2.0 Titanium At6,32000,380.00,5.0,Hatchback,Bs.as. G.b.a. Sur,hi,10,Ford Focus III,19884.0

In [ ]:
cars.shape

(10000, 15)

In [ ]:
cars = cars.drop(columns=['test', 'test1'])

In [ ]:
cars.shape

(10000, 13)

In [ ]:
cars.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,new_data,YTD,brand_model,Miles
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,hi,12,Volkswagen Vento,62106.0
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320.00,2.0,Pick-Up,Entre Ríos,hi,12,Ford Ranger,86992.0
2,Volkswagen,Fox,2011,1.6 Trendline,132000,209.98,5.0,Hatchback,Bs.as. G.b.a. Sur,hi,13,Volkswagen Fox,82021.0
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798.00,4.0,Pick-Up,Neuquén,hi,7,Ford Ranger,8078.0
4,Volkswagen,Gol,2013,1.4 Power 83cv 3 p,107000,146.00,3.0,Hatchback,Córdoba,hi,11,Volkswagen Gol,66487.0

In [ ]:
cars.drop(columns='new_data', inplace=True) # with inplace-parameter

In [ ]:
cars.shape

(10000, 12)

In [ ]:
# if you run it again, because the columns 'test' and 'test1' do not exist
# it will throw an error
cars.drop(columns=['test', 'test1'])

When `inplace=True` is selected, the operation directly affects the original DataFrame. The changes are made ot hte DateFrame itself, and there is no need to assign the result back to a variable.

However, when `inplace=False`, the operation does not modify the original DataFrame. It retursn a new DataFrame with the specified columns or rows dropped.

In [ ]:
cars.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,YTD,brand_model,Miles
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,12,Volkswagen Vento,62106.0
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320.00,2.0,Pick-Up,Entre Ríos,12,Ford Ranger,86992.0
2,Volkswagen,Fox,2011,1.6 Trendline,132000,209.98,5.0,Hatchback,Bs.as. G.b.a. Sur,13,Volkswagen Fox,82021.0
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798.00,4.0,Pick-Up,Neuquén,7,Ford Ranger,8078.0
4,Volkswagen,Gol,2013,1.4 Power 83cv 3 p,107000,146.00,3.0,Hatchback,Córdoba,11,Volkswagen Gol,66487.0

In [ ]:
cars = cars.drop(columns=['brand_model', 'YTD'])
cars.head(2)

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,Miles
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360.0,4.0,Sedán,Córdoba,62106.0
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320.0,2.0,Pick-Up,Entre Ríos,86992.0

### Dropping specific rows

In [ ]:
cars.head(5)

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,Miles
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,62106.0
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320.00,2.0,Pick-Up,Entre Ríos,86992.0
2,Volkswagen,Fox,2011,1.6 Trendline,132000,209.98,5.0,Hatchback,Bs.as. G.b.a. Sur,82021.0
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798.00,4.0,Pick-Up,Neuquén,8078.0
4,Volkswagen,Gol,2013,1.4 Power 83cv 3 p,107000,146.00,3.0,Hatchback,Córdoba,66487.0

In [ ]:
cars.drop(labels=[1, 2]).head(4)

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,Miles
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360.0,4.0,Sedán,Córdoba,62106.0
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798.0,4.0,Pick-Up,Neuquén,8078.0
4,Volkswagen,Gol,2013,1.4 Power 83cv 3 p,107000,146.0,3.0,Hatchback,Córdoba,66487.0
5,Volkswagen,Amarok,2014,2.0 Cd Tdi 180cv 4x4 Highline C34,115000,790.0,4.0,Pick-Up,Buenos Aires Interior,71458.0

In [ ]:
# Note that cars dataset is not changed in place!
# This is because the inplace operator was not used.
cars.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,Miles
0,Volkswagen,Vento,2012,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,62106.0
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320.00,2.0,Pick-Up,Entre Ríos,86992.0
2,Volkswagen,Fox,2011,1.6 Trendline,132000,209.98,5.0,Hatchback,Bs.as. G.b.a. Sur,82021.0
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798.00,4.0,Pick-Up,Neuquén,8078.0
4,Volkswagen,Gol,2013,1.4 Power 83cv 3 p,107000,146.00,3.0,Hatchback,Córdoba,66487.0

### Exercise

1. Replace the brand name 'Volkswagen' with 'VW'

In [ ]:
# boolean indexing with .loc accessor.
cars.loc[cars['Make'] == 'Volkswagen', 'Make'] = 'VW'
cars.head()

NameError: name 'cars' is not defined

In [ ]:
# chained indexing

# Chained indexing can sometimes lead to problems with view versus copy,
# and it's generally recommended to avoid it in favor of more explicit methods like .loc
cars['Make'][cars['Make'] == 'Volkswagen'] = 'VW'
cars.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,Miles
0,VW,VW,2012,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,62106.0
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320.00,2.0,Pick-Up,Entre Ríos,86992.0
2,VW,VW,2011,1.6 Trendline,132000,209.98,5.0,Hatchback,Bs.as. G.b.a. Sur,82021.0
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798.00,4.0,Pick-Up,Neuquén,8078.0
4,VW,VW,2013,1.4 Power 83cv 3 p,107000,146.00,3.0,Hatchback,Córdoba,66487.0
...,...,...,...,...,...,...,...,...,...,...
9995,Ford,Focus III,2016,2.0 Se,67000,399.00,5.0,Hatchback,Bs.as. G.b.a. Oeste,41632.0
9996,VW,VW,2012,1.9 Trendline I 100cv,120000,240.00,4.0,Sedán,Buenos Aires Interior,74565.0
9997,Ford,Fiesta Kinetic Design,2012,1.6 Design 120cv Titanium,89000,250.00,5.0,Hatchback,Tucumán,55302.0
9998,Ford,Fiesta Kinetic Design,2013,1.6 Design 120cv Titanium,76000,295.00,5.0,Hatchback,Buenos Aires Interior,47224.0
9999,Ford,Focus III,2014,2.0 Titanium At6,32000,380.00,5.0,Hatchback,Bs.as. G.b.a. Sur,19884.0

2. Let's assume the price of the Ford Ranger from 2018 in Santa Fe is incorrect. Fix the value from 730000 to 800000.

In [ ]:
# check how many ford rangers in 2018 in santa fe there are
condition = (cars['Make'] == 'Ford') & \
    (cars['Model'] == 'Ranger') & \
    (cars['Year'] == 2018) & \
    (cars['Location'] == 'Santa Fe')
cars.loc[condition]

In [ ]:
# change using the .loc method
cars.loc[condition, 'Price'] = 800
cars.loc[condition]

3. Delete all rows from the city of 'Córdoba'
    * Use simple filtering to create a new dataframe without those rows
    * Try to use the 'drop' function

In [ ]:
# using simple filtering
cars.loc[cars['Location'] != 'Córdoba']

In [ ]:
cars['Location'] == 'Córdoba' # column of booleans

In [ ]:
cars[cars['Location'] == 'Córdoba'] # filtered df

In [ ]:
cars[cars['Location'] == 'Córdoba'].index # index of df

In [ ]:
# using the drop function
cars.drop(cars[cars['Location'] == 'Córdoba'].index, inplace=False)

# Row transformations

### Simple if/else scenarios

In [ ]:
cars.loc[:, 'Make'] == 'Ford'

0       False
1        True
2       False
3        True
4       False
        ...
9995     True
9996    False
9997     True
9998     True
9999     True
Name: Make, Length: 10000, dtype: bool

In [ ]:
np.where(cars.loc[:, 'Make'] == 'Ford', 1, 0)

array([0, 1, 0, ..., 1, 1, 1])

In [ ]:
cars.loc[:, 'is_Ford_car'] = np.where(cars.loc[:, 'Make'] == 'Ford', 1, 0)
cars.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,Miles,is_Ford_car
0,VW,VW,2012,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,62106.0,0
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320.00,2.0,Pick-Up,Entre Ríos,86992.0,1
2,VW,VW,2011,1.6 Trendline,132000,209.98,5.0,Hatchback,Bs.as. G.b.a. Sur,82021.0,0
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798.00,4.0,Pick-Up,Neuquén,8078.0,1
4,VW,VW,2013,1.4 Power 83cv 3 p,107000,146.00,3.0,Hatchback,Córdoba,66487.0,0

### Custom transformations single column

In [ ]:
def my_custom_uppercase(kind):
  return kind.upper()

In [ ]:
my_custom_uppercase('hello')

'HELLO'

In [ ]:
cars.loc[:, 'Kind'].apply(my_custom_uppercase)

0           SEDÁN
1         PICK-UP
2       HATCHBACK
3         PICK-UP
4       HATCHBACK
          ...
9995    HATCHBACK
9996        SEDÁN
9997    HATCHBACK
9998    HATCHBACK
9999    HATCHBACK
Name: Kind, Length: 10000, dtype: object

In [ ]:
cars.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,Miles,is_Ford_car
0,VW,VW,2012,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,62106.0,0
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320.00,2.0,Pick-Up,Entre Ríos,86992.0,1
2,VW,VW,2011,1.6 Trendline,132000,209.98,5.0,Hatchback,Bs.as. G.b.a. Sur,82021.0,0
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798.00,4.0,Pick-Up,Neuquén,8078.0,1
4,VW,VW,2013,1.4 Power 83cv 3 p,107000,146.00,3.0,Hatchback,Córdoba,66487.0,0

In [ ]:
cars.loc[:, 'Kind'].apply(lambda kind: kind + ' hello')

0           Sedán hello
1         Pick-Up hello
2       Hatchback hello
3         Pick-Up hello
4       Hatchback hello
             ...
9995    Hatchback hello
9996        Sedán hello
9997    Hatchback hello
9998    Hatchback hello
9999    Hatchback hello
Name: Kind, Length: 10000, dtype: object

In [ ]:
cars.loc[:, 'Kind'].apply(lambda kind: kind.upper())

0           SEDÁN
1         PICK-UP
2       HATCHBACK
3         PICK-UP
4       HATCHBACK
          ...
9995    HATCHBACK
9996        SEDÁN
9997    HATCHBACK
9998    HATCHBACK
9999    HATCHBACK
Name: Kind, Length: 10000, dtype: object

In [ ]:
cars.loc[:, 'Kind'].apply(lambda kind: my_custom_uppercase(kind))

0           SEDÁN
1         PICK-UP
2       HATCHBACK
3         PICK-UP
4       HATCHBACK
          ...
9995    HATCHBACK
9996        SEDÁN
9997    HATCHBACK
9998    HATCHBACK
9999    HATCHBACK
Name: Kind, Length: 10000, dtype: object

In [ ]:
# 'lambda' is used to specify a so-called "anonymous function"
kind_uppercased = cars.loc[:, 'Kind'].apply(lambda kind: kind.upper())
kind_uppercased

0           SEDÁN
1         PICK-UP
2       HATCHBACK
3         PICK-UP
4       HATCHBACK
          ...
9995    HATCHBACK
9996        SEDÁN
9997    HATCHBACK
9998    HATCHBACK
9999    HATCHBACK
Name: Kind, Length: 10000, dtype: object

In [ ]:
cars.loc[:, 'kind_upper'] = kind_uppercased
cars.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,Miles,is_Ford_car,kind_upper
0,VW,VW,2012,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,62106.0,0,SEDÁN
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320.00,2.0,Pick-Up,Entre Ríos,86992.0,1,PICK-UP
2,VW,VW,2011,1.6 Trendline,132000,209.98,5.0,Hatchback,Bs.as. G.b.a. Sur,82021.0,0,HATCHBACK
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798.00,4.0,Pick-Up,Neuquén,8078.0,1,PICK-UP
4,VW,VW,2013,1.4 Power 83cv 3 p,107000,146.00,3.0,Hatchback,Córdoba,66487.0,0,HATCHBACK

### Custom transformations on the whole row

In [ ]:
cars

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,Miles,is_Ford_car,kind_upper
0,VW,VW,2012,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,62106.0,0,SEDÁN
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320.00,2.0,Pick-Up,Entre Ríos,86992.0,1,PICK-UP
2,VW,VW,2011,1.6 Trendline,132000,209.98,5.0,Hatchback,Bs.as. G.b.a. Sur,82021.0,0,HATCHBACK
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798.00,4.0,Pick-Up,Neuquén,8078.0,1,PICK-UP
4,VW,VW,2013,1.4 Power 83cv 3 p,107000,146.00,3.0,Hatchback,Córdoba,66487.0,0,HATCHBACK
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Ford,Focus III,2016,2.0 Se,67000,399.00,5.0,Hatchback,Bs.as. G.b.a. Oeste,41632.0,1,HATCHBACK
9996,VW,VW,2012,1.9 Trendline I 100cv,120000,240.00,4.0,Sedán,Buenos Aires Interior,74565.0,0,SEDÁN
9997,Ford,Fiesta Kinetic Design,2012,1.6 Design 120cv Titanium,89000,250.00,5.0,Hatchback,Tucumán,55302.0,1,HATCHBACK
9998,Ford,Fiesta Kinetic Design,2013,1.6 Design 120cv Titanium,76000,295.00,5.0,Hatchback,Buenos Aires Interior,47224.0,1,HATCHBACK
9999,Ford,Focus III,2014,2.0 Titanium At6,32000,380.00,5.0,Hatchback,Bs.as. G.b.a. Sur,19884.0,1,HATCHBACK

In [ ]:
avg_price = cars.loc[:, 'Price'].mean()

def classify_car_quality(car_row):
  car_quality = None

  if car_row['Year'] > 2015 and car_row['Price'] < avg_price:
    car_quality = 'good'
  else:
    car_quality = 'bad'

  return car_quality

# use custom 'def' function for complex scenarios
cars.loc[:, 'car_quality'] = cars.apply(classify_car_quality, axis=1)
cars.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,Miles,is_Ford_car,kind_upper,car_quality
0,VW,VW,2012,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,62106.0,0,SEDÁN,bad
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320.00,2.0,Pick-Up,Entre Ríos,86992.0,1,PICK-UP,bad
2,VW,VW,2011,1.6 Trendline,132000,209.98,5.0,Hatchback,Bs.as. G.b.a. Sur,82021.0,0,HATCHBACK,bad
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798.00,4.0,Pick-Up,Neuquén,8078.0,1,PICK-UP,bad
4,VW,VW,2013,1.4 Power 83cv 3 p,107000,146.00,3.0,Hatchback,Córdoba,66487.0,0,HATCHBACK,bad

In [ ]:
cars[cars['car_quality'] == 'good'].head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,Miles,is_Ford_car,kind_upper,car_quality
113,VW,VW,2016,1.0 Move Up! 75cv,54000,240.0,3.0,Hatchback,Bs.as. G.b.a. Norte,33554.0,0,HATCHBACK,good
130,VW,VW,2017,1.6 Trenline 101cv,18000,285.0,4.0,Sedán,Capital Federal,11185.0,0,SEDÁN,good
152,VW,VW,2017,1.6 Trendline 101cv 3p,7500,290.0,3.0,Hatchback,Buenos Aires Interior,4660.0,0,HATCHBACK,good
175,VW,VW,2016,1.6 Serie 101cv 5p,27000,245.0,5.0,Hatchback,Capital Federal,16777.0,0,HATCHBACK,good
193,VW,VW,2016,1.6 Highline 101cv,51000,260.0,4.0,Sedán,Bs.as. G.b.a. Norte,31690.0,0,SEDÁN,good

In [ ]:
# use custom lamdba function for simple scenarios
cars.loc[:, 'car_quality'] = cars.apply(lambda row: 'good' if (row['Year'] > 2015) and (row['Price'] < avg_price) else 'bad', axis=1)
cars.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,Miles,is_Ford_car,kind_upper,car_quality
0,VW,VW,2012,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,62106.0,0,SEDÁN,bad
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320.00,2.0,Pick-Up,Entre Ríos,86992.0,1,PICK-UP,bad
2,VW,VW,2011,1.6 Trendline,132000,209.98,5.0,Hatchback,Bs.as. G.b.a. Sur,82021.0,0,HATCHBACK,bad
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798.00,4.0,Pick-Up,Neuquén,8078.0,1,PICK-UP,bad
4,VW,VW,2013,1.4 Power 83cv 3 p,107000,146.00,3.0,Hatchback,Córdoba,66487.0,0,HATCHBACK,bad

In [ ]:
car_quality_filter = (cars.loc[:, 'Year'] > 2015) & (cars.loc[:, 'Price'] < avg_price)

# use built-in functionality whenever available
cars.loc[:, 'car_quality'] = np.where(car_quality_filter, 'good', 'bad')
cars.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,Miles,is_Ford_car,kind_upper,car_quality
0,VW,VW,2012,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,62106.0,0,SEDÁN,bad
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320.00,2.0,Pick-Up,Entre Ríos,86992.0,1,PICK-UP,bad
2,VW,VW,2011,1.6 Trendline,132000,209.98,5.0,Hatchback,Bs.as. G.b.a. Sur,82021.0,0,HATCHBACK,bad
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798.00,4.0,Pick-Up,Neuquén,8078.0,1,PICK-UP,bad
4,VW,VW,2013,1.4 Power 83cv 3 p,107000,146.00,3.0,Hatchback,Córdoba,66487.0,0,HATCHBACK,bad

# Concatenating dataframes


```
pd.concat()
```

In [ ]:
cars.shape

(10000, 13)

In [ ]:
cars.head()

In [ ]:
cars_concat_columns = pd.concat([cars, cars], axis=1)

In [ ]:
cars_concat_columns.shape

(10000, 26)

In [ ]:
cars_concat_columns.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,Miles,...,Variant,Kms,Price,Doors,Kind,Location,Miles,is_Ford_car,kind_upper,car_quality
0,VW,VW,2012,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,62106.0,...,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,62106.0,0,SEDÁN,bad
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320.00,2.0,Pick-Up,Entre Ríos,86992.0,...,2.3 Cd Xl Plus 4x2,140000,320.00,2.0,Pick-Up,Entre Ríos,86992.0,1,PICK-UP,bad
2,VW,VW,2011,1.6 Trendline,132000,209.98,5.0,Hatchback,Bs.as. G.b.a. Sur,82021.0,...,1.6 Trendline,132000,209.98,5.0,Hatchback,Bs.as. G.b.a. Sur,82021.0,0,HATCHBACK,bad
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798.00,4.0,Pick-Up,Neuquén,8078.0,...,3.2 Cd Xls Tdci 200cv Automática,13000,798.00,4.0,Pick-Up,Neuquén,8078.0,1,PICK-UP,bad
4,VW,VW,2013,1.4 Power 83cv 3 p,107000,146.00,3.0,Hatchback,Córdoba,66487.0,...,1.4 Power 83cv 3 p,107000,146.00,3.0,Hatchback,Córdoba,66487.0,0,HATCHBACK,bad

In [ ]:
cars_concat_rows = pd.concat([cars,cars], axis=0)

In [ ]:
cars_concat_rows.shape

(20000, 13)

In [ ]:
first_row = cars.loc[:0, :]
first_row

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,Miles,is_Ford_car,kind_upper,car_quality
0,VW,VW,2012,2.5 Luxury 170cv,99950,360.0,4.0,Sedán,Córdoba,62106.0,0,SEDÁN,bad

In [ ]:
cars_concat_rows = pd.concat([first_row, cars], axis=0)

In [ ]:
cars_concat_rows.shape

(10001, 13)

In [ ]:
cars_concat_rows.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,Miles,is_Ford_car,kind_upper,car_quality
0,VW,VW,2012,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,62106.0,0,SEDÁN,bad
0,VW,VW,2012,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,62106.0,0,SEDÁN,bad
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320.00,2.0,Pick-Up,Entre Ríos,86992.0,1,PICK-UP,bad
2,VW,VW,2011,1.6 Trendline,132000,209.98,5.0,Hatchback,Bs.as. G.b.a. Sur,82021.0,0,HATCHBACK,bad
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798.00,4.0,Pick-Up,Neuquén,8078.0,1,PICK-UP,bad

In [ ]:
concat_unequal_rows = pd.concat([first_row, cars], axis=1)
concat_unequal_rows.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,Miles,...,Variant,Kms,Price,Doors,Kind,Location,Miles,is_Ford_car,kind_upper,car_quality
0,VW,VW,2012.0,2.5 Luxury 170cv,99950.0,360.0,4.0,Sedán,Córdoba,62106.0,...,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,62106.0,0,SEDÁN,bad
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.3 Cd Xl Plus 4x2,140000,320.00,2.0,Pick-Up,Entre Ríos,86992.0,1,PICK-UP,bad
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.6 Trendline,132000,209.98,5.0,Hatchback,Bs.as. G.b.a. Sur,82021.0,0,HATCHBACK,bad
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.2 Cd Xls Tdci 200cv Automática,13000,798.00,4.0,Pick-Up,Neuquén,8078.0,1,PICK-UP,bad
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.4 Power 83cv 3 p,107000,146.00,3.0,Hatchback,Córdoba,66487.0,0,HATCHBACK,bad

In [ ]:
concat_unequal_rows.shape

(10000, 26)

In [ ]:
cars_concat_rows.head()

In [ ]:
cars_concat_rows.reset_index(drop=True).head()

# Renaming columns

In [ ]:
cars.rename(columns={'is_Ford_car': 'Is Ford Car'}, inplace=True)
cars.head()

,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location,Miles,Is Ford Car,kind_upper,car_quality
0,VW,VW,2012,2.5 Luxury 170cv,99950,360.00,4.0,Sedán,Córdoba,62106.0,0,SEDÁN,bad
1,Ford,Ranger,2012,2.3 Cd Xl Plus 4x2,140000,320.00,2.0,Pick-Up,Entre Ríos,86992.0,1,PICK-UP,bad
2,VW,VW,2011,1.6 Trendline,132000,209.98,5.0,Hatchback,Bs.as. G.b.a. Sur,82021.0,0,HATCHBACK,bad
3,Ford,Ranger,2017,3.2 Cd Xls Tdci 200cv Automática,13000,798.00,4.0,Pick-Up,Neuquén,8078.0,1,PICK-UP,bad
4,VW,VW,2013,1.4 Power 83cv 3 p,107000,146.00,3.0,Hatchback,Córdoba,66487.0,0,HATCHBACK,bad

# Joining dataframes
Joining two datasets is the fundamental action to add additional information to your dataset.

An example: You have information on
- sales: `purchase_date`, `item-id`, `customer-id`, `count_purchases` (how often was the item purchased)
- customer: `customer-id`, `full_name`, `address`, `payment_method`
- items: `item-id`, `descriptive_name`, `category` (toy, sports equipment, etc), `price`

Each of the information lives in a separate table. To answer questions like "On which category do the customer spend most of their money?" or "Do we sell in a specific part of the country more toys than in other parts of the country?" we need to combine the information of all three tables.

This is done by "joins", in pandas it is called "merge".

The join is done using an identifyer - a key/ID or a name - appearing in both tables. In every row where the identifyer appears in both tables, we have a "match" and the information of both datasets can be joined.

The merged information appear as additional columns in the resulting dataframe.

The command for a join in pandas looks like this

```
result = pd.merge(sales, customer, how="left", on="Customer_ID")
result = sales.merge(customer, how="left", on="Customer_ID")
```
`sales` is the *left* table, `customer` is the *right* table. `how` defines the type of join, `on` the variable on which the join will be performed, the identifier.

`result` will have all *columns* from the left table and all *columns* from the right table. The identifyer is included only once. That means for our example result will have the columns  `purchase_date`, `item-id`, `customer-id`, `count_purchases`, `full_name`, `address`, `payment_method`.


We distinguish different types of joins. They define how many *rows* we have in the result.


- **Left Join:** The resulting table contains the complete left table and all matching records from the right table. Records where no match exist appear is NaN. A **right join** is the same as a left join where left and right table are swapped.
- **Outer Join:** The resulting table contains all records of the left table and all records of the right table. Not matching records are filled with NaN.
- **Inner Join:** The resulting table contains only records where a match of left and right table exist.

The type of joins are often illustrated by Venn diagrams where the right circle symbolizes the right table and the left circle the left table.


# Inner join
![left join](https://learn.microsoft.com/en-us/power-query/media/merge-queries-inner/inner-join-operation.png)

# Left outer join
![left join](https://docs.microsoft.com/de-de/power-query/images/left-outer-join-operation.png)

# Right outer join
![right join](https://learn.microsoft.com/en-us/power-query/media/merge-queries-right-outer/right-outer-join-operation.png)

# Full outer join
![outer join](https://learn.microsoft.com/en-us/power-query/media/merge-queries-full-outer/full-outer-join-operation.png)

**To** practice joins we will need to have a second dataframe which can be joined onto 'cars'. The dataframe is computed from 'cars' and has following properties
- Average price **in euros €** of car models per brand (brand = Make). Columns: `Make, Model, avg_price`
- 3 additional "invented" rows
- All cars from 'Mercedes Benz' are removed

In [ ]:
avg_model_prices = cars.groupby(['Make', 'Model'])['Price'].mean().reset_index()
avg_model_prices = avg_model_prices.rename(columns={'Price': 'avg_price'})
avg_model_prices = avg_model_prices.loc[avg_model_prices.loc[:, 'Make'] != 'Mercedes Benz', :]

invented_rows = pd.DataFrame(
    data = [('Ford', 'Lo', 158703.340), ('Ford', 'Hi', 324235.670), ('Ford', 'Cheap', 6533.700)],
    columns=['Make', 'Model', 'avg_price']
)

avg_model_prices = pd.concat([invented_rows, avg_model_prices], axis=0, ignore_index=True)

avg_model_prices.shape

In [ ]:
# avg_model_prices.head()

import numpy as np
print(np.nan + 1)

nan

### Left outer join

In [ ]:
left_join = pd.merge(cars, avg_model_prices, on=['Make', 'Model'], how='left')

In [ ]:
left_join.head()

In [ ]:
# A left join includes the complete left table. The result of a left join has therefore
# the same number of rows as the left table IF the join columns are unique in the right table.
cars.shape
print()
left_join.shape

In [ ]:
# avg_model_prices does not include entries for 'Mercedes Benz'
# Those rows are then filled with NaN in a left join
left_join.loc[left_join.loc[:, 'Make'] == 'Mercedes Benz', :].head()

In [ ]:
# The "invented" models from avg_model_prices don't exist in the cars dataset, so
# they also don't exist in the result
left_join.loc[left_join.loc[:, 'Model'] == 'Cheap', :]