In [ ]:
import pandas as pd

## Loading Data

In [6]:
df = pd.read_csv("https://drive.google.com/uc?id=1GWHKPdxVuqroKoKoB49zOEyfyLAwbzcc", encoding="latin1")

In [10]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2013-138688,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2011-110422,22-01-2011,24-01-2011,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2014-121258,27-02-2014,04-03-2014,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2014-121258,27-02-2014,04-03-2014,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2014-121258,27-02-2014,04-03-2014,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2014-119914,05-05-2014,10-05-2014,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [11]:
#  check data types and df metadata
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 3.4 MB

In [17]:
df_custom = pd.read_csv(
    "https://drive.google.com/uc?id=1GWHKPdxVuqroKoKoB49zOEyfyLAwbzcc",
    encoding='latin1',
    nrows=100, # read only first 100 rows
    index_col="Order ID", # set column as index
    parse_dates=["Order Date"], # convert string to datetime
    date_format="%d-%m-%Y", # specify date format
    usecols=['Order ID', 'Order Date', 'Category', 'Sales'] # specific columns only
    )

df_custom.info()

df_custom

<class 'pandas.DataFrame'>
Index: 100 entries, CA-2013-152156 to CA-2013-158568
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order Date  100 non-null    datetime64[us]
 1   Category    100 non-null    str
 2   Sales       100 non-null    float64
dtypes: datetime64[us](1), float64(1), str(1)
memory usage: 5.7 KB

               Order Date         Category     Sales
Order ID
CA-2013-152156 2013-11-09        Furniture  261.9600
CA-2013-152156 2013-11-09        Furniture  731.9400
CA-2013-138688 2013-06-13  Office Supplies   14.6200
US-2012-108966 2012-10-11        Furniture  957.5775
US-2012-108966 2012-10-11  Office Supplies   22.3680
...                   ...              ...       ...
US-2014-109484 2014-11-07  Office Supplies    5.6820
CA-2014-161018 2014-11-10        Furniture   96.5300
CA-2014-157833 2014-06-18  Office Supplies   51.3120
CA-2013-149223 2013-09-07  Office Supplies   77.8800
CA-2013-158568 2013-08-30  Office Supplies   64.6240

[100 rows x 3 columns]

## Descriptive statistics

In [33]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [36]:
# Frequency counts for categorical variables
df[["Category"]].value_counts()

Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

In [39]:
# Specific percentile / quantile metrics on financial metrics
df["Sales"].quantile(0.75)

np.float64(209.94)

In [40]:
# Scalar aggregations across specific metrics
df["Sales"].sum()

np.float64(2297200.8603)

In [41]:
# maximum
df["Sales"].max()

np.float64(22638.48)

In [42]:
# standard deviation
df["Sales"].std()

np.float64(623.2451005086808)

## Indexing

In [43]:
# set index to "Order ID" column
df_indexed = df.set_index("Order ID")

# select one row by its index
df_indexed.loc["US-2012-108966"]

,Row ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Order ID,,,,,,,,,,,,,,,,,,,,
US-2012-108966,4,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
US-2012-108966,5,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [45]:
df_indexed

,Row ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Order ID,,,,,,,,,,,,,,,,,,,,
CA-2013-152156,1,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
CA-2013-152156,2,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
CA-2013-138688,3,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
US-2012-108966,4,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
US-2012-108966,5,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CA-2011-110422,9990,22-01-2011,24-01-2011,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
CA-2014-121258,9991,27-02-2014,04-03-2014,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
CA-2014-121258,9992,27-02-2014,04-03-2014,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
CA-2014-121258,9993,27-02-2014,04-03-2014,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
CA-2014-119914,9994,05-05-2014,10-05-2014,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [47]:
# sort index in descending order
df_indexed.sort_index(ascending=False)

,Row ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Order ID,,,,,,,,,,,,,,,,,,,,
US-2014-169551,5930,08-07-2014,10-07-2014,First Class,RL-19615,Rob Lucas,Consumer,United States,Philadelphia,Pennsylvania,19120,East,FUR-BO-10001519,Furniture,Bookcases,O'Sullivan 3-Shelf Heavy-Duty Bookcases,87.210,3,0.5,-45.3492
US-2014-169551,5931,08-07-2014,10-07-2014,First Class,RL-19615,Rob Lucas,Consumer,United States,Philadelphia,Pennsylvania,19120,East,OFF-PA-10004100,Office Supplies,Paper,Xerox 216,15.552,3,0.2,5.4432
US-2014-169551,5932,08-07-2014,10-07-2014,First Class,RL-19615,Rob Lucas,Consumer,United States,Philadelphia,Pennsylvania,19120,East,TEC-PH-10001363,Technology,Phones,Apple iPhone 5S,683.988,2,0.4,-113.9980
US-2014-169551,5933,08-07-2014,10-07-2014,First Class,RL-19615,Rob Lucas,Consumer,United States,Philadelphia,Pennsylvania,19120,East,OFF-ST-10004835,Office Supplies,Storage,Plastic Stacking Crates & Casters,13.392,3,0.2,1.0044
US-2014-169551,5934,08-07-2014,10-07-2014,First Class,RL-19615,Rob Lucas,Consumer,United States,Philadelphia,Pennsylvania,19120,East,TEC-AC-10002018,Technology,Accessories,AmazonBasics 3-Button USB Wired Mouse,16.776,3,0.2,4.8231
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CA-2011-100328,3084,29-01-2011,04-02-2011,Standard Class,JC-15340,Jasper Cacioppo,Consumer,United States,New York City,New York,10024,East,OFF-BI-10000343,Office Supplies,Binders,"Pressboard Covers with Storage Hooks, 9 1/2"" x...",3.928,1,0.2,1.3257
CA-2011-100293,9515,14-03-2011,18-03-2011,Standard Class,NF-18475,Neil Französisch,Home Office,United States,Jacksonville,Florida,32216,South,OFF-PA-10000176,Office Supplies,Paper,Xerox 1887,91.056,6,0.2,31.8696
CA-2011-100090,6288,08-07-2011,12-07-2011,Standard Class,EB-13705,Ed Braxton,Corporate,United States,San Francisco,California,94122,West,FUR-TA-10003715,Furniture,Tables,Hon 2111 Invitation Series Corner Table,502.488,3,0.2,-87.9354
CA-2011-100090,6289,08-07-2011,12-07-2011,Standard Class,EB-13705,Ed Braxton,Corporate,United States,San Francisco,California,94122,West,OFF-BI-10001597,Office Supplies,Binders,"Wilson Jones Ledger-Size, Piano-Hinge Binder, ...",196.704,6,0.2,68.8464
CA-2011-100006,2718,07-09-2011,13-09-2011,Standard Class,DK-13375,Dennis Kane,Consumer,United States,New York City,New York,10024,East,TEC-PH-10002075,Technology,Phones,AT&T EL51110 DECT,377.970,3,0.0,109.6113

In [48]:
# reset_index() restores "Order ID" back as a standard column
df_reset = df_indexed.reset_index()
df_reset

,Order ID,Row ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2013-152156,1,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,CA-2013-152156,2,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,CA-2013-138688,3,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,US-2012-108966,4,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,US-2012-108966,5,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,CA-2011-110422,9990,22-01-2011,24-01-2011,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,CA-2014-121258,9991,27-02-2014,04-03-2014,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,CA-2014-121258,9992,27-02-2014,04-03-2014,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,CA-2014-121258,9993,27-02-2014,04-03-2014,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,CA-2014-119914,9994,05-05-2014,10-05-2014,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [ ]:
# keep "Order ID" as a column as well
df_indexed = df.set_index("Order ID", drop=False)
df_indexed

## Renaming and Reordeing columns

In [49]:
# column names - copy, past and edit for the following steps
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [51]:
df[['Customer Name', 'Segment', 'Country']]

         Customer Name    Segment        Country
0          Claire Gute   Consumer  United States
1          Claire Gute   Consumer  United States
2      Darrin Van Huff  Corporate  United States
3       Sean O'Donnell   Consumer  United States
4       Sean O'Donnell   Consumer  United States
...                ...        ...            ...
9989  Tom Boeckenhauer   Consumer  United States
9990       Dave Brooks   Consumer  United States
9991       Dave Brooks   Consumer  United States
9992       Dave Brooks   Consumer  United States
9993      Chris Cortes   Consumer  United States

[9994 rows x 3 columns]

In [53]:
# Renaming specific columns using a dictionary mapping
df_renamed = df.rename(
    columns={
    "Sales": "Sales_USD",
    "Profit": "Net_Profit_USD",
    "Discount": "Discount_Rate"
})

df_renamed.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales_USD', 'Quantity', 'Discount_Rate',
       'Net_Profit_USD'],
      dtype='str')

In [54]:
# select and reorder specific columns
df_reorder = df_renamed[["Order ID", "Order Date", "Category", "Sales_USD", "Net_Profit_USD", "Discount_Rate"]]
df_reorder

,Order ID,Order Date,Category,Sales_USD,Net_Profit_USD,Discount_Rate
0,CA-2013-152156,09-11-2013,Furniture,261.9600,41.9136,0.00
1,CA-2013-152156,09-11-2013,Furniture,731.9400,219.5820,0.00
2,CA-2013-138688,13-06-2013,Office Supplies,14.6200,6.8714,0.00
3,US-2012-108966,11-10-2012,Furniture,957.5775,-383.0310,0.45
4,US-2012-108966,11-10-2012,Office Supplies,22.3680,2.5164,0.20
...,...,...,...,...,...,...
9989,CA-2011-110422,22-01-2011,Furniture,25.2480,4.1028,0.20
9990,CA-2014-121258,27-02-2014,Furniture,91.9600,15.6332,0.00
9991,CA-2014-121258,27-02-2014,Technology,258.5760,19.3932,0.20
9992,CA-2014-121258,27-02-2014,Office Supplies,29.6000,13.3200,0.00
9993,CA-2014-119914,05-05-2014,Office Supplies,243.1600,72.9480,0.00

## Select Columns

In [ ]:
# select one column
df["Category"]

In [ ]:
# select multiple columns
df[["Category", "Sales"]]

### filter()

In [57]:
# filter can be used to select columns by name or by a pattern in the column names
df.filter(items=["Category", "Sales"])

# you can filter the columns name for a sub-string
df.filter(like="Date")
df.filter(like="ID")

      Row ID        Order ID Customer ID       Product ID
0          1  CA-2013-152156    CG-12520  FUR-BO-10001798
1          2  CA-2013-152156    CG-12520  FUR-CH-10000454
2          3  CA-2013-138688    DV-13045  OFF-LA-10000240
3          4  US-2012-108966    SO-20335  FUR-TA-10000577
4          5  US-2012-108966    SO-20335  OFF-ST-10000760
...      ...             ...         ...              ...
9989    9990  CA-2011-110422    TB-21400  FUR-FU-10001889
9990    9991  CA-2014-121258    DB-13060  FUR-FU-10000747
9991    9992  CA-2014-121258    DB-13060  TEC-PH-10003645
9992    9993  CA-2014-121258    DB-13060  OFF-PA-10004041
9993    9994  CA-2014-119914    CC-12220  OFF-AP-10002684

[9994 rows x 4 columns]

In [58]:
# regex pattern to select columns starting with "Order"
df.filter(regex="^Order.*")

            Order ID  Order Date
0     CA-2013-152156  09-11-2013
1     CA-2013-152156  09-11-2013
2     CA-2013-138688  13-06-2013
3     US-2012-108966  11-10-2012
4     US-2012-108966  11-10-2012
...              ...         ...
9989  CA-2011-110422  22-01-2011
9990  CA-2014-121258  27-02-2014
9991  CA-2014-121258  27-02-2014
9992  CA-2014-121258  27-02-2014
9993  CA-2014-119914  05-05-2014

[9994 rows x 2 columns]

In [59]:
# or look for column names with a hyphen in them
df.filter(regex=".*-.*")

     Sub-Category
0       Bookcases
1          Chairs
2          Labels
3          Tables
4         Storage
...           ...
9989  Furnishings
9990  Furnishings
9991       Phones
9992        Paper
9993   Appliances

[9994 rows x 1 columns]

## Selcting Rows
`.loc()` and `.iloc()` select rows wherby:
- .loc selects by label (what's printed on the screen), while 
- .iloc selects by integer position (0-indexed location, like standard Python lists)

A label can be an integer which makes it sometimes hard to distinguish from a positional index.

In [ ]:
# select row by index
df.iloc[0]

#select by row label
df_indexed.loc["CA-2013-152156"]

Confusion arises if the deliberatly set index is the same a the default position. For example the first row of your data frame has the default index position 0 and the index you set also starts at zero, and your index is an integer. There is no visible difference between the two, but they are very different because label names are not positional indices.

In [ ]:
# selcting row by label or index position yields the same only for default index
df.loc[0] == df.iloc[0]

Another trap is a label based index that looks like a number but actually is a string.

In [63]:
df_postalindex = df.set_index(str("Postal Code"))
# df_postalindex.iloc[42420] # won't work
df_postalindex.loc[42420].head(2) # will work because the index is now a string type, not an integer

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Postal Code,,,,,,,,,,,,,,,,,,,,
42420,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
42420,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

### Slicing

In [64]:
# select multiple rows by index, excluding the last index
df.iloc[0:3]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820
2,3,CA-2013-138688,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714

In [65]:
# select multiple rows by index, including the last index
df_indexed.loc[["CA-2013-152156", "CA-2014-119914"]]

,Row ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Order ID,,,,,,,,,,,,,,,,,,,,
CA-2013-152156,1,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
CA-2013-152156,2,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820
CA-2014-119914,9994,05-05-2014,10-05-2014,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.0,72.9480

In [66]:
# slicing by label
df_indexed.loc["CA-2013-152156" : "CA-2013-138688"]

,Row ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Order ID,,,,,,,,,,,,,,,,,,,,
CA-2013-152156,1,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
CA-2013-152156,2,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820
CA-2013-138688,3,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714

In [ ]:
df.loc["row", "column"]

In [69]:
# selecting by label and selecting specific columns
df_indexed.loc[["CA-2013-138688"], ["Customer ID", "Category", "Sales", "Profit"]]

               Customer ID         Category  Sales  Profit
Order ID
CA-2013-138688    DV-13045  Office Supplies  14.62  6.8714

In [70]:
# slicing rows & columns
df_indexed.loc["CA-2013-152156": "US-2012-108966", "Category":"Sales"]

,Category,Sub-Category,Product Name,Sales
Order ID,,,,
CA-2013-152156,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
CA-2013-152156,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
CA-2013-138688,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
US-2012-108966,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
US-2012-108966,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [73]:
df_indexed.loc["CA-2013-152156", "Category"]

Order ID
CA-2013-152156    Furniture
CA-2013-152156    Furniture
Name: Category, dtype: str

## Selecting Scalars

The `at[]` and `iat[]` functions are designed for high-speed access to a single values.

In [77]:
df.head(1)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,999.0,2,0.0,41.9136

In [ ]:
# at[] — by label
df.at[0, "Sales"] = 999        # set value at row 0, column "Sales"
df.at[0, "Sales"]              # get value at row 0, column "Sales"

In [ ]:

# iat[] — by position
df.iat[0, 3] = "12-11-2013"    # set value at row 0, column position 3
df.iat[0, 3]                   # get value at row 0, column position 3

In [ ]:
## Boolean Indexing & Advanced Filtering

In [85]:
df[~(df["Sales"] < 5000.0)]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
165,166,CA-2011-139892,08-09-2011,12-09-2011,Standard Class,BM-11140,Becky Martin,Consumer,United States,San Antonio,...,78207,Central,TEC-MA-10000822,Technology,Machines,Lexmark MX611dhe Monochrome Laser Printer,8159.952,8,0.4,-1359.9920
509,510,CA-2012-145352,16-03-2012,22-03-2012,Standard Class,CM-12385,Christopher Martinez,Consumer,United States,Atlanta,...,30318,South,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,6354.950,5,0.0,3177.4750
683,684,US-2014-168116,05-11-2014,05-11-2014,Same Day,GT-14635,Grant Thornton,Corporate,United States,Burlington,...,27217,South,TEC-MA-10004125,Technology,Machines,Cubify CubeX 3D Printer Triple Head Print,7999.980,4,0.5,-3839.9904
2505,2506,CA-2011-143917,25-07-2011,27-07-2011,Second Class,KL-16645,Ken Lonsdale,Consumer,United States,San Francisco,...,94122,West,OFF-SU-10000151,Office Supplies,Supplies,High Speed Automatic Electric Letter Opener,8187.650,5,0.0,327.5060
2623,2624,CA-2014-127180,23-10-2014,25-10-2014,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,...,10024,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888
2697,2698,CA-2011-145317,18-03-2011,23-03-2011,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,...,32216,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784
4098,4099,CA-2011-116904,23-09-2011,28-09-2011,Standard Class,SC-20095,Sanjit Chand,Consumer,United States,Minneapolis,...,55407,Central,OFF-BI-10001120,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,9449.950,5,0.0,4630.4755
4190,4191,CA-2014-166709,18-11-2014,23-11-2014,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,19711,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856
4277,4278,US-2013-107440,17-04-2013,21-04-2013,Standard Class,BS-11365,Bill Shonely,Corporate,United States,Lakewood,...,8701,East,TEC-MA-10001047,Technology,Machines,"3D Systems Cube Printer, 2nd Generation, Magenta",9099.930,7,0.0,2365.9818
6340,6341,CA-2014-143112,06-10-2014,10-10-2014,Standard Class,TS-21370,Todd Sumrall,Corporate,United States,New York City,...,10035,East,TEC-MA-10001047,Technology,Machines,"3D Systems Cube Printer, 2nd Generation, Magenta",5199.960,4,0.0,1351.9896
6425,6426,CA-2013-143714,24-05-2013,28-05-2013,Standard Class,CC-12370,Christopher Conant,Consumer,United States,Philadelphia,...,19120,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,8399.976,4,0.4,1119.9968
6520,6521,CA-2014-138289,17-01-2014,19-01-2014,Second Class,AR-10540,Andy Reiter,Consumer,United States,Jackson,...,49201,Central,OFF-BI-10004995,Office Supplies,Binders,GBC DocuBind P400 Electric Binding System,5443.960,4,0.0,2504.2216
6626,6627,CA-2011-145541,14-12-2011,21-12-2011,Standard Class,TB-21400,Tom Boeckenhauer,Consumer,United States,New York City,...,10024,East,TEC-MA-10001127,Technology,Machines,HP Designjet T520 Inkjet Large Format Printer ...,6999.960,4,0.0,2239.9872
6826,6827,CA-2013-118689,03-10-2013,10-10-2013,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760
7666,7667,US-2013-140158,05-10-2013,09-10-2013,Standard Class,DR-12940,Daniel Raglin,Home Office,United States,Providence,...,2908,East,TEC-CO-10001449,Technology,Copiers,Hewlett Packard LaserJet 3310 Copier,5399.910,9,0.0,2591.9568
8153,8154,CA-2014-140151,24-03-2014,26-03-2014,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808
8488,8489,CA-2013-158841,02-02-2013,04-02-2013,Second Class,SE-20110,Sanjit Engle,Consumer,United States,Arlington,...,22204,South,TEC-MA-10001127,Technology,Machines,HP Designjet T520 Inkjet Large Format Printer ...,8749.950,5,0.0,2799.9840
8858,8859,CA-2014-135909,14-10-2014,21-10-2014,Standard Class,JW-15220,Jane Waco,Corporate,United States,Sacramento,...,95823,West,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,5083.960,5,0.2,1906.4850
9039,9040,CA-2013-117121,18-12-2013,22-12-2013,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Detroit,...,48205,Central,OFF-BI-10000545,Office Supplies,Binders,GBC Ibimaster 500 Manual ProClick Binding System,9892.740,13,0.0,4946.3700

In [ ]:
# boolean filter: Orders with Sales greater than $500
high_sales_mask = df["Sales"] > 1500.0
df[high_sales_mask].head(3)

Boolean filtering with multiple conditions using logical operators: AND (&), OR (|), NOT (~).

Enclose each condition in parentheses due to Python operator precedence.

combine filters or negate conditions with ~

#to answer e.g. who are the customers in the South region with Profit greater than $1500, but not in the Corporate segment?

In [ ]:
complex_filter = (df["Region"] == "South") & (df["Profit"] > 1500) & ~ (df["Segment"]== "Corporate")

df[complex_filter]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
509,510,CA-2012-145352,16-03-2012,22-03-2012,Standard Class,CM-12385,Christopher Martinez,Consumer,United States,Atlanta,...,30318,South,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,6354.95,5,0.0,3177.475
8488,8489,CA-2013-158841,02-02-2013,04-02-2013,Second Class,SE-20110,Sanjit Engle,Consumer,United States,Arlington,...,22204,South,TEC-MA-10001127,Technology,Machines,HP Designjet T520 Inkjet Large Format Printer ...,8749.95,5,0.0,2799.984

In [93]:
# check membership filtering with .isin()
region_mask = df["Region"].isin(["East", "West"])
df[region_mask].head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2,3,CA-2013-138688,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714
5,6,CA-2011-115812,09-06-2011,14-06-2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.86,7,0.0,14.1694
6,7,CA-2011-115812,09-06-2011,14-06-2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.28,4,0.0,1.9656

In [ ]:
# string accessor boolean evaluation (.str.startswith, .str.contains)
subcat_mask = df["Product Name"].str.contains("tool") | df["City"].str.contains("Berlin")
df[subcat_mask]