In [1]:
import pandas as pd

## Loading Data

In [37]:
df = pd.read_csv("https://drive.google.com/uc?id=1GWHKPdxVuqroKoKoB49zOEyfyLAwbzcc", encoding='latin1')

In [ ]:
#  check data types and df metadata
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [ ]:
df_custom = pd.read_csv(
    "https://drive.google.com/uc?id=1GWHKPdxVuqroKoKoB49zOEyfyLAwbzcc",
    encoding='latin1',
    nrows=100, # read only first 100 rows
    index_col="Order ID", # set column as index
    parse_dates=["Order Date"], # convert string to datetime
    date_format="%d-%m-%Y", # specify date format
    usecols=['Order ID', 'Order Date', 'Category', 'Sales'] # specific columns only
    )

df_custom.info()

<class 'pandas.DataFrame'>
Index: 100 entries, CA-2013-152156 to CA-2013-158568
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order Date  100 non-null    datetime64[us]
 1   Category    100 non-null    str
 2   Sales       100 non-null    float64
dtypes: datetime64[us](1), float64(1), str(1)
memory usage: 3.1+ KB

## Descriptive statistics

In [ ]:
# Frequency counts for categorical variables
df["Category"].value_counts()

Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

In [ ]:
# Specific percentile / quantile metrics on financial metrics
df["Sales"].quantile(0.90)

np.float64(572.7060000000001)

In [32]:
# Scalar aggregations across specific metrics
df["Sales"].sum()

np.float64(2297200.8603)

In [33]:
# maximum
df["Sales"].max()

np.float64(22638.48)

In [34]:
# standard deviation
df["Sales"].std()

np.float64(623.2451005086808)

## Indexing

In [ ]:
# set index to "Order ID" column
df_indexed = df.set_index("Order ID")

# select one row by its index
df_indexed.loc["US-2012-108966"]

,Row ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Order ID,,,,,,,,,,,,,,,,,,,,
US-2012-108966,4,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
US-2012-108966,5,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
# sort index in descending order
df_indexed.sort_index(ascending=False)

,Row ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Order ID,,,,,,,,,,,,,,,,,,,,
US-2014-169551,5935,08-07-2014,10-07-2014,First Class,RL-19615,Rob Lucas,Consumer,United States,Philadelphia,Pennsylvania,19120,East,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,527.920,2,0.2,85.7870
US-2014-169551,5934,08-07-2014,10-07-2014,First Class,RL-19615,Rob Lucas,Consumer,United States,Philadelphia,Pennsylvania,19120,East,TEC-AC-10002018,Technology,Accessories,AmazonBasics 3-Button USB Wired Mouse,16.776,3,0.2,4.8231
US-2014-169551,5931,08-07-2014,10-07-2014,First Class,RL-19615,Rob Lucas,Consumer,United States,Philadelphia,Pennsylvania,19120,East,OFF-PA-10004100,Office Supplies,Paper,Xerox 216,15.552,3,0.2,5.4432
US-2014-169551,5932,08-07-2014,10-07-2014,First Class,RL-19615,Rob Lucas,Consumer,United States,Philadelphia,Pennsylvania,19120,East,TEC-PH-10001363,Technology,Phones,Apple iPhone 5S,683.988,2,0.4,-113.9980
US-2014-169551,5933,08-07-2014,10-07-2014,First Class,RL-19615,Rob Lucas,Consumer,United States,Philadelphia,Pennsylvania,19120,East,OFF-ST-10004835,Office Supplies,Storage,Plastic Stacking Crates & Casters,13.392,3,0.2,1.0044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CA-2011-100328,3084,29-01-2011,04-02-2011,Standard Class,JC-15340,Jasper Cacioppo,Consumer,United States,New York City,New York,10024,East,OFF-BI-10000343,Office Supplies,Binders,"Pressboard Covers with Storage Hooks, 9 1/2"" x...",3.928,1,0.2,1.3257
CA-2011-100293,9515,14-03-2011,18-03-2011,Standard Class,NF-18475,Neil Französisch,Home Office,United States,Jacksonville,Florida,32216,South,OFF-PA-10000176,Office Supplies,Paper,Xerox 1887,91.056,6,0.2,31.8696
CA-2011-100090,6288,08-07-2011,12-07-2011,Standard Class,EB-13705,Ed Braxton,Corporate,United States,San Francisco,California,94122,West,FUR-TA-10003715,Furniture,Tables,Hon 2111 Invitation Series Corner Table,502.488,3,0.2,-87.9354
CA-2011-100090,6289,08-07-2011,12-07-2011,Standard Class,EB-13705,Ed Braxton,Corporate,United States,San Francisco,California,94122,West,OFF-BI-10001597,Office Supplies,Binders,"Wilson Jones Ledger-Size, Piano-Hinge Binder, ...",196.704,6,0.2,68.8464
CA-2011-100006,2718,07-09-2011,13-09-2011,Standard Class,DK-13375,Dennis Kane,Consumer,United States,New York City,New York,10024,East,TEC-PH-10002075,Technology,Phones,AT&T EL51110 DECT,377.970,3,0.0,109.6113

In [ ]:
# reset_index() restores "Order ID" back as a standard column
df_reset = df_indexed.reset_index()
df_reset

,Order ID,Row ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2013-152156,1,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,CA-2013-152156,2,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,CA-2013-138688,3,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,US-2012-108966,4,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,US-2012-108966,5,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,CA-2011-110422,9990,22-01-2011,24-01-2011,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,CA-2014-121258,9991,27-02-2014,04-03-2014,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,CA-2014-121258,9992,27-02-2014,04-03-2014,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,CA-2014-121258,9993,27-02-2014,04-03-2014,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,CA-2014-119914,9994,05-05-2014,10-05-2014,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [ ]:
# keep "Order ID" as a column as well
df_indexed = df.set_index("Order ID", drop=False)
df_indexed

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Order ID,,,,,,,,,,,,,,,,,,,,,
CA-2013-152156,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
CA-2013-152156,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
CA-2013-138688,3,CA-2013-138688,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
US-2012-108966,4,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
US-2012-108966,5,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CA-2011-110422,9990,CA-2011-110422,22-01-2011,24-01-2011,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
CA-2014-121258,9991,CA-2014-121258,27-02-2014,04-03-2014,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
CA-2014-121258,9992,CA-2014-121258,27-02-2014,04-03-2014,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
CA-2014-121258,9993,CA-2014-121258,27-02-2014,04-03-2014,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
CA-2014-119914,9994,CA-2014-119914,05-05-2014,10-05-2014,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

## Renaming and Reordeing columns

In [ ]:
# column names - copy, past and edit for the following steps
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [ ]:
# Renaming specific columns using a dictionary mapping
df_renamed = df.rename(columns={
    "Sales": "Sales_USD",
    "Profit": "Net_Profit_USD",
    "Discount": "Discount_Rate"
})

df_renamed.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales_USD', 'Quantity', 'Discount_Rate',
       'Net_Profit_USD'],
      dtype='str')

In [ ]:
# select and reorder specific columns
df_reorder = df_renamed[["Order ID", "Order Date", "Category", "Sales_USD", "Net_Profit_USD", "Discount_Rate"]]
df_reorder

,Order ID,Order Date,Category,Sales_USD,Net_Profit_USD,Discount_Rate
0,CA-2013-152156,09-11-2013,Furniture,261.9600,41.9136,0.00
1,CA-2013-152156,09-11-2013,Furniture,731.9400,219.5820,0.00
2,CA-2013-138688,13-06-2013,Office Supplies,14.6200,6.8714,0.00
3,US-2012-108966,11-10-2012,Furniture,957.5775,-383.0310,0.45
4,US-2012-108966,11-10-2012,Office Supplies,22.3680,2.5164,0.20
...,...,...,...,...,...,...
9989,CA-2011-110422,22-01-2011,Furniture,25.2480,4.1028,0.20
9990,CA-2014-121258,27-02-2014,Furniture,91.9600,15.6332,0.00
9991,CA-2014-121258,27-02-2014,Technology,258.5760,19.3932,0.20
9992,CA-2014-121258,27-02-2014,Office Supplies,29.6000,13.3200,0.00
9993,CA-2014-119914,05-05-2014,Office Supplies,243.1600,72.9480,0.00

## Select Columns

In [ ]:
# select one column
df["Category"]

             Category     Sales
0           Furniture  261.9600
1           Furniture  731.9400
2     Office Supplies   14.6200
3           Furniture  957.5775
4     Office Supplies   22.3680
...               ...       ...
9989        Furniture   25.2480
9990        Furniture   91.9600
9991       Technology  258.5760
9992  Office Supplies   29.6000
9993  Office Supplies  243.1600

[9994 rows x 2 columns]

In [ ]:
# select multiple columns
df[["Category", "Sales"]]

### filter()

In [ ]:
# filter can be used to select columns by name or by a pattern in the column names
df.filter(items=["Category", "Sales"])

# you can filter the columns name for a sub-string
df.filter(like="ID")
df.filter(like="Date")

# regex pattern to select columns starting with "Order"
df.filter(regex="^Order.*")

# or look for column names with a hyphen in them
df.filter(regex=".*-.*")

     Sub-Category
0       Bookcases
1          Chairs
2          Labels
3          Tables
4         Storage
...           ...
9989  Furnishings
9990  Furnishings
9991       Phones
9992        Paper
9993   Appliances

[9994 rows x 1 columns]

## Selcting Rows
`.loc()` and `.iloc()` select rows wherby:
- .loc selects by label (what's printed on the screen), while 
- .iloc selects by integer position (0-indexed location, like standard Python lists)

A label can be an integer which makes it sometimes hard to distinguish from a positional index.

In [ ]:
# select row by index
df.iloc[0]

#select by row label
df_indexed.loc["CA-2013-152156"]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Order ID,,,,,,,,,,,,,,,,,,,,,
CA-2013-152156,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
CA-2013-152156,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

Confusion arises if the deliberatly set index is the same a the default position. For example the first row of your data frame has the default index position 0 and the index you set also starts at zero, and your index is an integer. There is no visible difference between the two, but they are very different because label names are not positional indices.

In [89]:
# selcting row by label or index position yields the same only for default index
df.loc[0] == df.iloc[0]

Row ID           True
Order ID         True
Order Date       True
Ship Date        True
Ship Mode        True
Customer ID      True
Customer Name    True
Segment          True
Country          True
City             True
State            True
Postal Code      True
Region           True
Product ID       True
Category         True
Sub-Category     True
Product Name     True
Sales            True
Quantity         True
Discount         True
Profit           True
Name: 0, dtype: bool

Another trap is a label based index that looks like a number but actually is a string.

In [108]:
df_postalindex = df.set_index(str("Postal Code"))
# df_postalindex.iloc[42420] # won't work
df_postalindex.loc[42420].head(2) # will work because the index is now a string type, not an integer

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Postal Code,,,,,,,,,,,,,,,,,,,,
42420,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
42420,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

### Slicing

In [128]:
# select multiple rows by index, excluding the last index
df.iloc[0:3]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820
2,3,CA-2013-138688,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714

In [129]:
# select multiple rows by index, including the last index
df_indexed.loc[["CA-2013-152156", "CA-2014-119914"]]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Order ID,,,,,,,,,,,,,,,,,,,,,
CA-2013-152156,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
CA-2013-152156,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820
CA-2014-119914,9994,CA-2014-119914,05-05-2014,10-05-2014,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.0,72.9480

In [140]:
# slicing by label
df_indexed.loc["CA-2013-152156": "CA-2013-138688"]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Order ID,,,,,,,,,,,,,,,,,,,,,
CA-2013-152156,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
CA-2013-152156,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820
CA-2013-138688,3,CA-2013-138688,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714

In [ ]:
# selecting by label and selecting specific columns
df_indexed.loc["CA-2013-138688", ["Customer ID", "Category", "Sales", "Profit"]]

Customer ID           DV-13045
Category       Office Supplies
Sales                    14.62
Profit                  6.8714
Name: CA-2013-138688, dtype: object

In [144]:
# slicing rows & columns
df_indexed.loc["CA-2013-152156": "US-2012-108966", "Category":"Sales"]

,Category,Sub-Category,Product Name,Sales
Order ID,,,,
CA-2013-152156,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
CA-2013-152156,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
CA-2013-138688,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
US-2012-108966,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
US-2012-108966,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

## Selecting Scalars

The `at[]` and `iat[]` functions are designed for high-speed access to a single values.

In [150]:
# at[] — by label
df.at[0, "Sales"] = 999        # set value at row 0, column "Sales"
df.at[0, "Sales"]              # get value at row 0, column "Sales"

np.float64(999.0)

In [ ]:

# iat[] — by position
df.iat[0, 3] = "12-11-2013"    # set value at row 0, column position 3
df.iat[0, 3]                   # get value at row 0, column position 3

'12-11-2013'

In [156]:
## Boolean Indexing & Advanced Filtering

In [191]:
# boolean filter: Orders with Sales greater than $500
high_sales_mask = df["Sales"] > 1500.0
df[high_sales_mask].head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
10,11,CA-2011-115812,09-06-2011,14-06-2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.184,9,0.2,85.3092
27,28,US-2012-150630,17-09-2012,21-09-2012,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.430,7,0.5,-1665.0522
149,150,CA-2013-114489,06-12-2013,10-12-2013,Standard Class,JE-16165,Justin Ellison,Corporate,United States,Franklin,...,53132,Central,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",1951.840,8,0.0,585.5520

Boolean filtering with multiple conditions using logical operators: AND (&), OR (|), NOT (~).

Enclose each condition in parentheses due to Python operator precedence.

combine filters or negate conditions with ~

#to answer e.g. who are the customers in the South region with Profit greater than $1500, but not in the Corporate segment?

In [172]:
complex_filter = (df["Region"] == "South") & (df["Profit"] > 1500) & ~ (df["Segment"]== "Corporate")
df[complex_filter]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
509,510,CA-2012-145352,16-03-2012,22-03-2012,Standard Class,CM-12385,Christopher Martinez,Consumer,United States,Atlanta,...,30318,South,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,6354.95,5,0.0,3177.475
8488,8489,CA-2013-158841,02-02-2013,04-02-2013,Second Class,SE-20110,Sanjit Engle,Consumer,United States,Arlington,...,22204,South,TEC-MA-10001127,Technology,Machines,HP Designjet T520 Inkjet Large Format Printer ...,8749.95,5,0.0,2799.984

In [173]:
# check membership filtering with .isin()
region_mask = df["Region"].isin(["East", "West"])
df[region_mask].head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2,3,CA-2013-138688,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714
5,6,CA-2011-115812,09-06-2011,14-06-2011,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.86,7,0.0,14.1694

In [190]:
# string accessor boolean evaluation (.str.startswith, .str.contains)
subcat_mask = df["Product Name"].str.contains("tool") | df["City"].str.contains("Berlin")
df[subcat_mask]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1841,1842,CA-2013-157763,19-07-2013,24-07-2013,Standard Class,KH-16330,Katharine Harms,Corporate,United States,Bowling Green,...,42104,South,FUR-CH-10000988,Furniture,Chairs,Hon Olson Stacker Stools,140.810,1,0.0,39.4268
2447,2448,CA-2013-119165,01-11-2013,07-11-2013,Standard Class,BD-11320,Bill Donatelli,Consumer,United States,Philadelphia,...,19143,East,FUR-CH-10000988,Furniture,Chairs,Hon Olson Stacker Stools,492.835,5,0.3,-14.0810
2751,2752,CA-2011-158029,26-05-2011,30-05-2011,Standard Class,HF-14995,Herbert Flentye,Consumer,United States,Los Angeles,...,90008,West,FUR-CH-10000988,Furniture,Chairs,Hon Olson Stacker Stools,225.296,2,0.2,22.5296
2857,2858,CA-2013-154690,16-08-2013,18-08-2013,Second Class,CC-12370,Christopher Conant,Consumer,United States,Fayetteville,...,28314,South,FUR-CH-10000988,Furniture,Chairs,Hon Olson Stacker Stools,225.296,2,0.2,22.5296
3426,3427,CA-2012-153381,24-09-2012,28-09-2012,Standard Class,DE-13255,Deanra Eno,Home Office,United States,Dubuque,...,52001,Central,FUR-CH-10000988,Furniture,Chairs,Hon Olson Stacker Stools,1408.100,10,0.0,394.2680
3768,3769,CA-2011-153913,16-12-2011,20-12-2011,Second Class,KB-16585,Ken Black,Corporate,United States,Hialeah,...,33012,South,FUR-CH-10000988,Furniture,Chairs,Hon Olson Stacker Stools,1013.832,9,0.2,101.3832
4250,4251,CA-2011-168130,19-09-2011,19-09-2011,Same Day,BS-11365,Bill Shonely,Corporate,United States,New York City,...,10011,East,FUR-CH-10000988,Furniture,Chairs,Hon Olson Stacker Stools,887.103,7,0.1,177.4206
5779,5780,CA-2011-105270,11-11-2011,18-11-2011,Standard Class,AP-10915,Arthur Prichep,Consumer,United States,Los Angeles,...,90008,West,FUR-CH-10000988,Furniture,Chairs,Hon Olson Stacker Stools,112.648,1,0.2,11.2648
6284,6285,CA-2013-100944,25-09-2013,29-09-2013,Standard Class,EH-13765,Edward Hooks,Corporate,United States,Los Angeles,...,90049,West,FUR-CH-10000988,Furniture,Chairs,Hon Olson Stacker Stools,563.240,5,0.2,56.3240
6699,6700,CA-2014-145429,22-07-2014,26-07-2014,Standard Class,SW-20455,Shaun Weien,Consumer,United States,San Diego,...,92024,West,FUR-CH-10000988,Furniture,Chairs,Hon Olson Stacker Stools,225.296,2,0.2,22.5296